### ISSUE TITLE
git-annex-testremote with SSH IO to localhost ~80x slower than filesystem IO

### ISSUE THREAD

**Issue by mih** [datalad/git-annex-ria-remote#2]
This is consistent across travis runs and my local machine, so unlikely to be a specific configuration issue. A potential source for this slowness could be the SSH connection handling provided by DataLad (as hinted on in https://github.com/datalad/datalad/issues/3487). However, at the moment that is pure speculation.

It is also unclear at the moment, if this slowness is a general issue, or if this is an artifact of the specific procedures used by `testremote`, and/or whether it is limited to the test suite.

**Comment by mih** [comment]
Relaying an observation from @bpoldrack: In comparison with the `rsync` special remote that comes with `git-annex`, a `testremote` invocation is not substantially slower. Hence the slowness of this test seems to be causes by the sheer number of SSH calls that are performed.

**Comment by bpoldrack** [comment]
Yes. FTR:

Locally `git annex testremote rsync-over-ssh` results in `All 568 tests passed (1427.10s)` and `git annex testremote ria-remote` in `All 517 tests passed (1713.33s)`. Not sure, why the number of tests is different. However, while it is a bit slower, I don't think it's our `SSHManager` or `SSHConnection` that is to blame. Ran some tests with additional debug messages including timestamps. The actual call to `ssh` (or `scp` respectively) was logged at the same microsecond as the RIARemote's `put`/`get` method. So, if anything the `Runner` might cause some slow down.

**Comment by mih** [comment]
I think we can safely close this now. We are not doing something fundamentally stupid.
