### ISSUE TITLE
Decide on destiny of remote shell's stderr

### ISSUE THREAD

**Issue by bpoldrack** [datalad/git-annex-ria-remote#20]
https://github.com/datalad/git-annex-ria-remote/pull/19 changed remote execution to take place via a remote shell. While this generally works, we still need to decide on some details, especially error handling. We don't check the shell's stderr ATM. This might be fine or not. Either way it should be finalized. If we don't need stderr, because we figure, that we raise `RemoteError` (or return False) anyway and evaluation of stderr is pointless, we then should simply throw stderr away by not piping but redirecting to `/dev/null`.
If we figure we need it, then there's a bit more to do in order to be able to read from it properly (it's blocking mode ATM). Meaning: We then need start-/end-markers therein as well.

**Comment by mih** [comment]
What is the status here? We will shortly use this in production.

**Comment by bpoldrack** [comment]
We need to throw away stderr as long as we don't reimplement based on asyncio or sth similar.
In that sense decision made.
