### ISSUE TITLE
Marker for ongoing transfers

### ISSUE THREAD

**Issue by mih** [datalad/git-annex-ria-remote#24]
ATM there is no way to see if a transfer is going on from the server-side. This would be necessary if server-side processing is to be performed (e.g. moving keys into an `archive.7z`).

We could change the upload location to not be `Path(key_dir) / key / key + '_'`, but instead use a dedicated transfer folder, such that only complete keys end up in `annex/objects`. With this behavior, no further marker would be necessary (e.g. `annex/transfer/key`).

**Comment by bpoldrack** [comment]
Dedicated folder sounds good. How about not risking (future) namespace conflict with annex folders by using `ria-remote/transfer/key` instead?

**Comment by mih** [comment]
Sounds good! Can you implement this change?
