### ISSUE TITLE
Twine check fails on 0.6 release

### ISSUE THREAD

**Issue by mih** [datalad/git-annex-ria-remote#29]
Like this:

```
% twine check dist/ria_remote-0.6-py2.py3-none-any.whl 
Checking dist/ria_remote-0.6-py2.py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 86: Error: Unexpected indentation.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
```

@effigies Can you spot my mistake. I roughly followed you packaging guide. Thx!

**Comment by effigies** [comment]
Old setuptools?

**Comment by effigies** [comment]
Need 38.6.0+. https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/#3-upgrade-your-setuptools

**Comment by mih** [comment]
Here is what I have:

```
% pip show setuptools
Name: setuptools
Version: 41.6.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /home/mih/env/datalad3-dev/lib/python3.7/site-packages
Requires: 
Required-by: zope.interface, twine, Sphinx, PyHamcrest, ipython, ipdb

```

Twine is 2.0.0
Wheel is 0.33.6

**Comment by mih** [comment]
Maybe it has something to do with the specification of multiple maintainers?

**Comment by bpoldrack** [comment]
FTR: Line number is off. Content of setup.cfg is counted. Got rid of the actual error by having no indentation for the toplevel of that tree depiction (https://github.com/datalad/git-annex-ria-remote/blame/78fd5002a66eb16ae8aca93b6f02c1ae36d960e2/README.md#L72)

However, that warning about a missing `long_description_content_type` remains for now.

**Comment by effigies** [comment]
Moving back to single author and maintainer fixes the twine check. I would probably report to twine that they're giving a bad message in this case.

FWIW, these fields are all `str`, not `list-comma`: https://setuptools.readthedocs.io/en/latest/setuptools.html#metadata

**Comment by effigies** [comment]
```diff
diff --git a/setup.cfg b/setup.cfg
index 05fb350..279a34b 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,19 +1,11 @@
 [metadata]
 url = https://github.com/datalad/git-annex-ria-remote
-author =
-    Michael Hanke
-    Benjamin Poldrack
-author_email =
-    michael.hanke@gmail.com
-    benjaminpoldrack@gmail.com
-maintainer =
-    Michael Hanke
-    Benjamin Poldrack
-maintainer_email =
-    michael.hanke@gmail.com
-    benjaminpoldrack@gmail.com
+author = Michael Hanke
+author_email = michael.hanke@gmail.com
+maintainer = Michael Hanke
+maintainer_email = michael.hanke@gmail.com
 description = Git-annex special remote implementation for (remote) indexed archives
-#long_description = file:README.md
+long_description = file:README.md
 long_description_content_type = text/markdown; charset=UTF-8
 license = MIT
 classifiers =
```

**Comment by bpoldrack** [comment]
True. Interestingly I tried this by just outcommenting the second entry which didn't work. So it's the line break that messes things up. Also, despite it not being `list-comma`, twine doesn't complain if we provide a comma-separated list. (I'd assume that it still is treated as a single entry, of course)
