### ISSUE TITLE
Helper script to turn local .git/annex/objects into archive.7z

### ISSUE THREAD

**Issue by mih** [datalad/git-annex-ria-remote#7]
This should be relatively straightforward to implement.

- iterate over all keys
- compute `hashdirlower` subdirectories as described in https://git-annex.branchable.com/internals/hashing
- build temp dir with desired structure (hardlinks?)
- 7z the thing

**Comment by mih** [comment]
Need to check if this is still relevant.

**Comment by mih** [comment]
It is still relevant, the layout use "directory-remote"-style hashdirlower, while a local annex would use "mixed".

**Comment by bpoldrack** [comment]
This should be easily extractable from the tests, which do exactly this IIRC.
